version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - licy-php
  
  nginx:
    image: nginx:latest
    ports:
      - "88:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - licy-php

networks:
  app-php:
    driver: bridge